drop table if exists bookmarks;

create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title text,
    url text,
    description text,
    rating numeric    
);

insert into bookmarks (title, url, description, rating)
values 
    ('Thinkful', 'https://www.thinkful.com', 'Think outside the classroom', '5' ),
    ('Google', 'https://www.google.com', 'Where we find everything else', '4' ),
    ('MDN', 'https://developer.mozilla.org', 'The only place to find web documentation','5'),
    ('Youtube', 'https://www.youtube.com', 'Funny animal videos and lots of ads', '4'),
    ('Facebook', 'https://facebook.com', 'Where wine moms rule and science does not', '1'),
    ('Instgram', 'https://instagram.com', 'Photoshop yourseld to fame', '3'),
    ('Twitter', 'https://twitter.com', 'Shitposts all day every day', '5'),
    ('LinkedIn', 'https://linkedin.com', 'Get a job', '3'),
    ('Mywebsite', 'http://hello.com', 'filler', '1'),
    ('Another filler', 'http://hellome.com', 'just like a lot of naruto', '1');
    